apiVersion: apps/v1
kind: Deployment
metadata:
  name: eleve-backend
spec:
  replicas: 2          # This tells K8s: ALWAYS keep 2 backend containers running!
  selector:
    matchLabels:
      app: eleve-backend
  template:
    metadata:
      labels:
        app: eleve-backend
    spec:
      containers:
      - name: eleve-backend
        image: eleveecom-backend:latest
        imagePullPolicy: Never  # Tells K8s to use the local Docker image you already built
        ports:
        - containerPort: 5001
        env:
        - name: MONGO_DB_URI
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: MONGO_DB_URI
